os:
  - linux
  - osx
language: node_js
node_js:
  - '10'
  - '12'
before_script:
  - npm install winston@2.3.1
  - npm install iobroker.js-controller --production
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
